### ISSUE TITLE
Projects appearing as both mining and oil

### ISSUE THREAD

**Issue by davidmihalyi** [NRGI/resource-projects-dataload#19]
Arroyo Seco (and many more projects) appear twice.

Arroyo Seco Mexico  Oil and Gas 1
Arroyo Seco Mexico  Mining  1

The original data displays it as mining on two occasion, which could create duplicate, but never as oil.
Should be displayed as one mining project.

**Comment by caprenter** [comment]
There is something odd coming through in the data here:
Notice there are two 'base_def:hasCommodity' values
One is blank, but becomes Oil and Gas on click through. The other is minerals
http://lodspeakr-live.nrgi-dev2.default.opendataservices.uk0.bigv.io/default-view/http/resourceprojects.org/project/MX/arse-vk8nzb

**Comment by timgdavies** [comment]
Ok. This issue seems to be coming from:
- The fact commodity identifiers are built from the name of the commodity;
- The commodity type is attached from the neighbouring column in the spreadsheet;
- If we get just a commodity type, with no commodity name, we end up with an ID of http://resourceprojects.org/commodity/ which then gets the commodityType attached

Over time we end up with just about every commodityType attached to http://resourceprojects.org/commodity/ which breaks things.

A query level fix would be to filter out http://resourceprojects.org/commodity/

E.g. 

```
FILTER(?commodity != <http://resourceprojects.org/commodity/>) 
```

At the data input level, I think this is probably best handled by a TagLifter tweak so that if it finds the anticipated inputs for constructing an ID blank it reverts to assigning a random ID.

**Comment by caprenter** [comment]
Just a note that this seems to be 'fixed' as far as the front-end goes
